//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Custom Color....
        /// </summary>
        internal static string AddCustomColor {
            get {
                return ResourceManager.GetString("AddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add Hex Color....
        /// </summary>
        internal static string AddCustomHexColor {
            get {
                return ResourceManager.GetString("AddCustomHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a successfully added to dictionary.
        /// </summary>
        internal static string AddCustomWordSuccess {
            get {
                return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add to dictionary.
        /// </summary>
        internal static string AddToDictionary {
            get {
                return ResourceManager.GetString("AddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The content you are trying to paste has MS Word formatting.
        ///Would you like to clean it?.
        /// </summary>
        internal static string AskWordCleaning {
            get {
                return ResourceManager.GetString("AskWordCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string CancelTable {
            get {
                return ResourceManager.GetString("CancelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell Properties.
        /// </summary>
        internal static string CellProperties {
            get {
                return ResourceManager.GetString("CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select a cell to set its properties!.
        /// </summary>
        internal static string CellWarning {
            get {
                return ResourceManager.GetString("CellWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Manually.
        /// </summary>
        internal static string ChangeWordString {
            get {
                return ResourceManager.GetString("ChangeWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CSS Class.
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All HTML Tags.
        /// </summary>
        internal static string ClearAllHtmlTags {
            get {
                return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Class.
        /// </summary>
        internal static string ClearClass {
            get {
                return ResourceManager.GetString("ClearClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cascading Style Sheets.
        /// </summary>
        internal static string ClearCssFormatting {
            get {
                return ResourceManager.GetString("ClearCssFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Tags.
        /// </summary>
        internal static string ClearFontTags {
            get {
                return ResourceManager.GetString("ClearFontTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Formatting.
        /// </summary>
        internal static string ClearFormatting {
            get {
                return ResourceManager.GetString("ClearFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Span Tags.
        /// </summary>
        internal static string ClearSpanTags {
            get {
                return ResourceManager.GetString("ClearSpanTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Style.
        /// </summary>
        internal static string ClearStyle {
            get {
                return ResourceManager.GetString("ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Microsoft Word Formatting.
        /// </summary>
        internal static string ClearWordFormatting {
            get {
                return ResourceManager.GetString("ClearWordFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spelling Changes.
        /// </summary>
        internal static string CorrectSpelling {
            get {
                return ResourceManager.GetString("CorrectSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Link.
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dialogs.
        /// </summary>
        internal static string DialogToolbar {
            get {
                return ResourceManager.GetString("DialogToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dropdowns.
        /// </summary>
        internal static string DropdownToolbar {
            get {
                return ResourceManager.GetString("DropdownToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enhanced Edit.
        /// </summary>
        internal static string EnhancedEditToolbar {
            get {
                return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The added HTML code exceeded the character limit.
        /// </summary>
        internal static string ExceededHtmlLength {
            get {
                return ResourceManager.GetString("ExceededHtmlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The added text exceeded the character limit.
        /// </summary>
        internal static string ExceededTextLength {
            get {
                return ResourceManager.GetString("ExceededTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open file...
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save as....
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Button.
        /// </summary>
        internal static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Checkbox.
        /// </summary>
        internal static string FormCheckbox {
            get {
                return ResourceManager.GetString("FormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error! Form elements are only supported when the content area is set to Iframe!.
        /// </summary>
        internal static string FormElementsAreSupportedByIframeError {
            get {
                return ResourceManager.GetString("FormElementsAreSupportedByIframeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Form.
        /// </summary>
        internal static string FormForm {
            get {
                return ResourceManager.GetString("FormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hidden.
        /// </summary>
        internal static string FormHidden {
            get {
                return ResourceManager.GetString("FormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Radio button.
        /// </summary>
        internal static string FormRadio {
            get {
                return ResourceManager.GetString("FormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string FormReset {
            get {
                return ResourceManager.GetString("FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Submit.
        /// </summary>
        internal static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Textbox.
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Textarea.
        /// </summary>
        internal static string FormTextarea {
            get {
                return ResourceManager.GetString("FormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RadEditor._getAllSheets called with no document object provided!.
        /// </summary>
        internal static string GetAllSheetsCalledWithNoDocumentError {
            get {
                return ResourceManager.GetString("GetAllSheetsCalledWithNoDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTML Mode.
        /// </summary>
        internal static string HtmlMode {
            get {
                return ResourceManager.GetString("HtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignore All.
        /// </summary>
        internal static string IgnoreAllString {
            get {
                return ResourceManager.GetString("IgnoreAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ignore.
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select an image to set its image map properties!.
        /// </summary>
        internal static string ImageMapWarning {
            get {
                return ResourceManager.GetString("ImageMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indent HTML.
        /// </summary>
        internal static string IndentHtml {
            get {
                return ResourceManager.GetString("IndentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Toolbar.
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This word occurs more than once in the text. Would you like to replace all instances?.
        /// </summary>
        internal static string MoreThanOnceMessage {
            get {
                return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move.
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No mistakes found..
        /// </summary>
        internal static string NoSpellingMistakes {
            get {
                return ResourceManager.GetString("NoSpellingMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (no suggestions).
        /// </summary>
        internal static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, provide the custom color HEX value:.
        /// </summary>
        internal static string PromptColor {
            get {
                return ResourceManager.GetString("PromptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Design.
        /// </summary>
        internal static string RadEditorDesignMode {
            get {
                return ResourceManager.GetString("RadEditorDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content....
        /// </summary>
        internal static string RadEditorGroupboxContent {
            get {
                return ResourceManager.GetString("RadEditorGroupboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string RadEditorGroupboxTitle {
            get {
                return ResourceManager.GetString("RadEditorGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HTML.
        /// </summary>
        internal static string RadEditorHtmlMode {
            get {
                return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        internal static string RadEditorPreviewMode {
            get {
                return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, reduce the content of the field.
        /// </summary>
        internal static string ReduceTheConentLength {
            get {
                return ResourceManager.GetString("ReduceTheConentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize Object.
        /// </summary>
        internal static string ResizeCommand {
            get {
                return ResourceManager.GetString("ResizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set HTML.
        /// </summary>
        internal static string SetHtml {
            get {
                return ResourceManager.GetString("SetHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error! Set EditorContentAreaMode to Iframe if you want to edit full page HTML!.
        /// </summary>
        internal static string SetToIframeForFullHTMLError {
            get {
                return ResourceManager.GetString("SetToIframeForFullHTMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show toolbar.
        /// </summary>
        internal static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Spell Check is complete!.
        /// </summary>
        internal static string SpellCheckComplete {
            get {
                return ResourceManager.GetString("SpellCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finish spellchecking.
        /// </summary>
        internal static string SpellCheckEnd {
            get {
                return ResourceManager.GetString("SpellCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spelling Change.
        /// </summary>
        internal static string SpellingChange {
            get {
                return ResourceManager.GetString("SpellingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spell checking in progress....
        /// </summary>
        internal static string SpellingInProgress {
            get {
                return ResourceManager.GetString("SpellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spell checking mode. Misspelled words are highlighted in yellow..
        /// </summary>
        internal static string SpellingMode {
            get {
                return ResourceManager.GetString("SpellingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table.
        /// </summary>
        internal static string TableToolbar {
            get {
                return ResourceManager.GetString("TableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, select a table to set its properties!.
        /// </summary>
        internal static string TableWarning {
            get {
                return ResourceManager.GetString("TableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RadEditor Toolbar.
        /// </summary>
        internal static string ToolbarCaption {
            get {
                return ResourceManager.GetString("ToolbarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This tool is not supported by Mozilla/Netscape browsers..
        /// </summary>
        internal static string ToolNotSupportedByNetscape {
            get {
                return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Typing....
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You cannot undo further while in spellcheck mode. Please finish spellchecking first..
        /// </summary>
        internal static string UndoDisabledMessage {
            get {
                return ResourceManager.GetString("UndoDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please use Ctrl+C to Copy.
        /// </summary>
        internal static string UseCtrlC {
            get {
                return ResourceManager.GetString("UseCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please use Ctrl+V to Paste.
        /// </summary>
        internal static string UseCtrlV {
            get {
                return ResourceManager.GetString("UseCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please use Ctrl+X to Cut.
        /// </summary>
        internal static string UseCtrlX {
            get {
                return ResourceManager.GetString("UseCtrlX", resourceCulture);
            }
        }
    }
}
