//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tools() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Tools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About RadEditor.
        /// </summary>
        internal static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Absolute Position.
        /// </summary>
        internal static string AbsolutePosition {
            get {
                return ResourceManager.GetString("AbsolutePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AJAX Spellchecker.
        /// </summary>
        internal static string AjaxSpellCheck {
            get {
                return ResourceManager.GetString("AjaxSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alignment selector.
        /// </summary>
        internal static string AlignmentSelector {
            get {
                return ResourceManager.GetString("AlignmentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply CSS Class.
        /// </summary>
        internal static string ApplyClass {
            get {
                return ResourceManager.GetString("ApplyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background Color.
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clipboard.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ColorPicker.
        /// </summary>
        internal static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert to lower case.
        /// </summary>
        internal static string ConvertToLower {
            get {
                return ResourceManager.GetString("ConvertToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert to upper case.
        /// </summary>
        internal static string ConvertToUpper {
            get {
                return ResourceManager.GetString("ConvertToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compliance Check.
        /// </summary>
        internal static string CSDialog {
            get {
                return ResourceManager.GetString("CSDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrease Size.
        /// </summary>
        internal static string DecreaseSize {
            get {
                return ResourceManager.GetString("DecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Cell.
        /// </summary>
        internal static string DeleteCell {
            get {
                return ResourceManager.GetString("DeleteCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Column.
        /// </summary>
        internal static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Row.
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Table.
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Document Manager.
        /// </summary>
        internal static string DocumentManager {
            get {
                return ResourceManager.GetString("DocumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editing.
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter Pressed.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find And Replace.
        /// </summary>
        internal static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flash Manager.
        /// </summary>
        internal static string FlashManager {
            get {
                return ResourceManager.GetString("FlashManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Name.
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Size.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Foreground Color.
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paragraph Style.
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format Code Block.
        /// </summary>
        internal static string FormatCodeBlock {
            get {
                return ResourceManager.GetString("FormatCodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format Painter.
        /// </summary>
        internal static string FormatPainter {
            get {
                return ResourceManager.GetString("FormatPainter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply Format.
        /// </summary>
        internal static string FormatPainterApply {
            get {
                return ResourceManager.GetString("FormatPainterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Format.
        /// </summary>
        internal static string FormatPainterClear {
            get {
                return ResourceManager.GetString("FormatPainterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Format.
        /// </summary>
        internal static string FormatPainterCopy {
            get {
                return ResourceManager.GetString("FormatPainterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format Sets.
        /// </summary>
        internal static string FormatSets {
            get {
                return ResourceManager.GetString("FormatSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Format Stripper.
        /// </summary>
        internal static string FormatStripper {
            get {
                return ResourceManager.GetString("FormatStripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Editor.
        /// </summary>
        internal static string ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Manager.
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image Map Editor.
        /// </summary>
        internal static string ImageMapDialog {
            get {
                return ResourceManager.GetString("ImageMapDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase Size.
        /// </summary>
        internal static string IncreaseSize {
            get {
                return ResourceManager.GetString("IncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Indent.
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Anchor.
        /// </summary>
        internal static string InsertAnchor {
            get {
                return ResourceManager.GetString("InsertAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Column to the Left.
        /// </summary>
        internal static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Column to the Right.
        /// </summary>
        internal static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Custom Links.
        /// </summary>
        internal static string InsertCustomLink {
            get {
                return ResourceManager.GetString("InsertCustomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Date.
        /// </summary>
        internal static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Email Link.
        /// </summary>
        internal static string InsertEmailLink {
            get {
                return ResourceManager.GetString("InsertEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert External Video.
        /// </summary>
        internal static string InsertExternalVideo {
            get {
                return ResourceManager.GetString("InsertExternalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Button.
        /// </summary>
        internal static string InsertFormButton {
            get {
                return ResourceManager.GetString("InsertFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Checkbox.
        /// </summary>
        internal static string InsertFormCheckbox {
            get {
                return ResourceManager.GetString("InsertFormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Form Element.
        /// </summary>
        internal static string InsertFormElement {
            get {
                return ResourceManager.GetString("InsertFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Form.
        /// </summary>
        internal static string InsertFormForm {
            get {
                return ResourceManager.GetString("InsertFormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Hidden.
        /// </summary>
        internal static string InsertFormHidden {
            get {
                return ResourceManager.GetString("InsertFormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Password.
        /// </summary>
        internal static string InsertFormPassword {
            get {
                return ResourceManager.GetString("InsertFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Radio.
        /// </summary>
        internal static string InsertFormRadio {
            get {
                return ResourceManager.GetString("InsertFormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Reset.
        /// </summary>
        internal static string InsertFormReset {
            get {
                return ResourceManager.GetString("InsertFormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Select.
        /// </summary>
        internal static string InsertFormSelect {
            get {
                return ResourceManager.GetString("InsertFormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Submit.
        /// </summary>
        internal static string InsertFormSubmit {
            get {
                return ResourceManager.GetString("InsertFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Textbox.
        /// </summary>
        internal static string InsertFormText {
            get {
                return ResourceManager.GetString("InsertFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Textarea.
        /// </summary>
        internal static string InsertFormTextarea {
            get {
                return ResourceManager.GetString("InsertFormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Groupbox.
        /// </summary>
        internal static string InsertGroupbox {
            get {
                return ResourceManager.GetString("InsertGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Horizontal Rule.
        /// </summary>
        internal static string InsertHorizontalRule {
            get {
                return ResourceManager.GetString("InsertHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Image.
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Link.
        /// </summary>
        internal static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Numbered List.
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Paragraph.
        /// </summary>
        internal static string InsertParagraph {
            get {
                return ResourceManager.GetString("InsertParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Row Above.
        /// </summary>
        internal static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Row Below.
        /// </summary>
        internal static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Code Snippet.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Symbol.
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Table.
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Table.
        /// </summary>
        internal static string InsertTableLight {
            get {
                return ResourceManager.GetString("InsertTableLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Time.
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bullet List.
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Align Center.
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Justify.
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Align Left.
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove alignment.
        /// </summary>
        internal static string JustifyNone {
            get {
                return ResourceManager.GetString("JustifyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Align Right.
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hyperlink Manager.
        /// </summary>
        internal static string LinkManager {
            get {
                return ResourceManager.GetString("LinkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Links.
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media.
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media Manager.
        /// </summary>
        internal static string MediaManager {
            get {
                return ResourceManager.GetString("MediaManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merge Cells Horizontally.
        /// </summary>
        internal static string MergeColumns {
            get {
                return ResourceManager.GetString("MergeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merge Cells Vertically.
        /// </summary>
        internal static string MergeRows {
            get {
                return ResourceManager.GetString("MergeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Module Manager.
        /// </summary>
        internal static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Outdent.
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Page Properties.
        /// </summary>
        internal static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste As Html.
        /// </summary>
        internal static string PasteAsHtml {
            get {
                return ResourceManager.GetString("PasteAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste from Word.
        /// </summary>
        internal static string PasteFromWord {
            get {
                return ResourceManager.GetString("PasteFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste from Word, strip font.
        /// </summary>
        internal static string PasteFromWordNoFontsNoSizes {
            get {
                return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste Html.
        /// </summary>
        internal static string PasteHtml {
            get {
                return ResourceManager.GetString("PasteHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste Markdown.
        /// </summary>
        internal static string PasteMarkdown {
            get {
                return ResourceManager.GetString("PasteMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste Plain Text.
        /// </summary>
        internal static string PastePlainText {
            get {
                return ResourceManager.GetString("PastePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paste Options.
        /// </summary>
        internal static string PasteStrip {
            get {
                return ResourceManager.GetString("PasteStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferences.
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proofing.
        /// </summary>
        internal static string Proofing {
            get {
                return ResourceManager.GetString("Proofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real font size.
        /// </summary>
        internal static string RealFontSize {
            get {
                return ResourceManager.GetString("RealFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Redo.
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Last Command.
        /// </summary>
        internal static string RepeatLastCommand {
            get {
                return ResourceManager.GetString("RepeatLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select All.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cell Properties.
        /// </summary>
        internal static string SetCellProperties {
            get {
                return ResourceManager.GetString("SetCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties....
        /// </summary>
        internal static string SetImageProperties {
            get {
                return ResourceManager.GetString("SetImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties....
        /// </summary>
        internal static string SetLinkProperties {
            get {
                return ResourceManager.GetString("SetLinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table Properties.
        /// </summary>
        internal static string SetTableProperties {
            get {
                return ResourceManager.GetString("SetTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Silverlight Manager.
        /// </summary>
        internal static string SilverlightManager {
            get {
                return ResourceManager.GetString("SilverlightManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spellchecker.
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Split Cell Vertically.
        /// </summary>
        internal static string SplitCell {
            get {
                return ResourceManager.GetString("SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Split Cell Horizontally.
        /// </summary>
        internal static string SplitCellHorizontal {
            get {
                return ResourceManager.GetString("SplitCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strikethrough.
        /// </summary>
        internal static string StrikeThrough {
            get {
                return ResourceManager.GetString("StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strip All Formatting.
        /// </summary>
        internal static string StripAll {
            get {
                return ResourceManager.GetString("StripAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strip Css Formatting.
        /// </summary>
        internal static string StripCss {
            get {
                return ResourceManager.GetString("StripCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strip Font Elements.
        /// </summary>
        internal static string StripFont {
            get {
                return ResourceManager.GetString("StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strip Span Elements.
        /// </summary>
        internal static string StripSpan {
            get {
                return ResourceManager.GetString("StripSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Strip Word Formatting.
        /// </summary>
        internal static string StripWord {
            get {
                return ResourceManager.GetString("StripWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Style Builder.
        /// </summary>
        internal static string StyleBuilder {
            get {
                return ResourceManager.GetString("StyleBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Styles.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subscript.
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SuperScript.
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tables.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Table Wizard.
        /// </summary>
        internal static string TableWizard {
            get {
                return ResourceManager.GetString("TableWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template Manager.
        /// </summary>
        internal static string TemplateManager {
            get {
                return ResourceManager.GetString("TemplateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dock all Floating Toolbars/Modules.
        /// </summary>
        internal static string ToggleDocking {
            get {
                return ResourceManager.GetString("ToggleDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Floating Toolbar.
        /// </summary>
        internal static string ToggleFloatingToolbar {
            get {
                return ResourceManager.GetString("ToggleFloatingToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Full Screen Mode.
        /// </summary>
        internal static string ToggleScreenMode {
            get {
                return ResourceManager.GetString("ToggleScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show/Hide Border.
        /// </summary>
        internal static string ToggleTableBorder {
            get {
                return ResourceManager.GetString("ToggleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [Obsolete] Track Changes.
        /// </summary>
        internal static string TrackChangesDialog {
            get {
                return ResourceManager.GetString("TrackChangesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Link.
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XHTML Validator.
        /// </summary>
        internal static string XhtmlValidator {
            get {
                return ResourceManager.GetString("XhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
