//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action.
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alignment.
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ToolTip.
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Background.
        /// </summary>
        internal static string bgColor {
            get {
                return ResourceManager.GetString("bgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Window.
        /// </summary>
        internal static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Border Width.
        /// </summary>
        internal static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Border color.
        /// </summary>
        internal static string borderColor {
            get {
                return ResourceManager.GetString("borderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CellPadding.
        /// </summary>
        internal static string cellPadding {
            get {
                return ResourceManager.GetString("cellPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CellSpacing.
        /// </summary>
        internal static string cellSpacing {
            get {
                return ResourceManager.GetString("cellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Classname.
        /// </summary>
        internal static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columns.
        /// </summary>
        internal static string cols {
            get {
                return ResourceManager.GetString("cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Doctype.
        /// </summary>
        internal static string Doctype {
            get {
                return ResourceManager.GetString("Doctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RemoveElement.
        /// </summary>
        internal static string DomInspectorRemoveElement {
            get {
                return ResourceManager.GetString("DomInspectorRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expand Report Pane.
        /// </summary>
        internal static string ExpandValidator {
            get {
                return ResourceManager.GetString("ExpandValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height.
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL.
        /// </summary>
        internal static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Media Pane.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid value. Please enter a number..
        /// </summary>
        internal static string NodeInspectorInvalidValue {
            get {
                return ResourceManager.GetString("NodeInspectorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected element is .
        /// </summary>
        internal static string NodeInspectorSelectedElement {
            get {
                return ResourceManager.GetString("NodeInspectorSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nowrap.
        /// </summary>
        internal static string noWrap {
            get {
                return ResourceManager.GetString("noWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parent Window.
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tag Inspector.
        /// </summary>
        internal static string RadEditorDomInspector {
            get {
                return ResourceManager.GetString("RadEditorDomInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Real-Time HTML View.
        /// </summary>
        internal static string RadEditorHtmlInspector {
            get {
                return ResourceManager.GetString("RadEditorHtmlInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Properties Inspector.
        /// </summary>
        internal static string RadEditorNodeInspector {
            get {
                return ResourceManager.GetString("RadEditorNodeInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        internal static string RadEditorStatistics {
            get {
                return ResourceManager.GetString("RadEditorStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XHTML Validator.
        /// </summary>
        internal static string RadEditorXhtmlValidator {
            get {
                return ResourceManager.GetString("RadEditorXhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rows.
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Pane.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Same Window.
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Characters:.
        /// </summary>
        internal static string StatisticsCharacters {
            get {
                return ResourceManager.GetString("StatisticsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Words:.
        /// </summary>
        internal static string StatisticsWords {
            get {
                return ResourceManager.GetString("StatisticsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Target.
        /// </summary>
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Browser Window.
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validate XHTML.
        /// </summary>
        internal static string ValidateXHTML {
            get {
                return ResourceManager.GetString("ValidateXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vertical Alignment.
        /// </summary>
        internal static string vAlign {
            get {
                return ResourceManager.GetString("vAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Value.
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width.
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
