//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadImageEditor {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadImageEditor.Dialogs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        internal static string AddText_Color {
            get {
                return ResourceManager.GetString("AddText_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The color of the text to add.
        /// </summary>
        internal static string AddText_ColorToolTip {
            get {
                return ResourceManager.GetString("AddText_ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Current Color is {0}).
        /// </summary>
        internal static string AddText_CurrentColorText {
            get {
                return ResourceManager.GetString("AddText_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Family.
        /// </summary>
        internal static string AddText_FontFamily {
            get {
                return ResourceManager.GetString("AddText_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The font family of the text to add.
        /// </summary>
        internal static string AddText_FontFamilyToolTip {
            get {
                return ResourceManager.GetString("AddText_FontFamilyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Font Size.
        /// </summary>
        internal static string AddText_FontSize {
            get {
                return ResourceManager.GetString("AddText_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The size of the text to add.
        /// </summary>
        internal static string AddText_FontSizeToolTip {
            get {
                return ResourceManager.GetString("AddText_FontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Color.
        /// </summary>
        internal static string AddText_PickColorToolTip {
            get {
                return ResourceManager.GetString("AddText_PickColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your text here....
        /// </summary>
        internal static string AddText_SampleText {
            get {
                return ResourceManager.GetString("AddText_SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Text.
        /// </summary>
        internal static string AddText_Title {
            get {
                return ResourceManager.GetString("AddText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string BrightnessContrast_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("BrightnessContrast_ApplyBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply the selected brightness/contrast levels to the image.
        /// </summary>
        internal static string BrightnessContrast_ApplyBtn_ToolTip {
            get {
                return ResourceManager.GetString("BrightnessContrast_ApplyBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string BrightnessContrast_ResetBtn_Text {
            get {
                return ResourceManager.GetString("BrightnessContrast_ResetBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset the changes so far.
        /// </summary>
        internal static string BrightnessContrast_ResetBtn_ToolTip {
            get {
                return ResourceManager.GetString("BrightnessContrast_ResetBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Brightness/Contrast.
        /// </summary>
        internal static string BrightnessContrast_Title {
            get {
                return ResourceManager.GetString("BrightnessContrast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between -100 and 100.
        /// </summary>
        internal static string Brightness_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Brightness_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actual Size.
        /// </summary>
        internal static string Common_ActualSize {
            get {
                return ResourceManager.GetString("Common_ActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string Common_Apply {
            get {
                return ResourceManager.GetString("Common_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Merge the drawn figure with the main canvas.
        /// </summary>
        internal static string Common_AppyDrawToolTip {
            get {
                return ResourceManager.GetString("Common_AppyDrawToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Best Fit.
        /// </summary>
        internal static string Common_BestFit {
            get {
                return ResourceManager.GetString("Common_BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Constrain Proportions?.
        /// </summary>
        internal static string Common_ConstrainProportions {
            get {
                return ResourceManager.GetString("Common_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decrease.
        /// </summary>
        internal static string Common_Decrease {
            get {
                return ResourceManager.GetString("Common_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A file with a name same as the target already exists!.
        /// </summary>
        internal static string Common_FileExists {
            get {
                return ResourceManager.GetString("Common_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Height.
        /// </summary>
        internal static string Common_Height {
            get {
                return ResourceManager.GetString("Common_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Increase.
        /// </summary>
        internal static string Common_Increase {
            get {
                return ResourceManager.GetString("Common_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert.
        /// </summary>
        internal static string Common_Insert {
            get {
                return ResourceManager.GetString("Common_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Left.
        /// </summary>
        internal static string Common_Left {
            get {
                return ResourceManager.GetString("Common_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cannot write to the target folder!.
        /// </summary>
        internal static string Common_MessageCannotWriteToFolder {
            get {
                return ResourceManager.GetString("Common_MessageCannotWriteToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The selected file could not be deleted because the application did not have enough permissions. Please, contact the administrator..
        /// </summary>
        internal static string Common_NoPermissionsToDeleteFile {
            get {
                return ResourceManager.GetString("Common_NoPermissionsToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Overwrite if file exists?.
        /// </summary>
        internal static string Common_OverwriteExisting {
            get {
                return ResourceManager.GetString("Common_OverwriteExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Position.
        /// </summary>
        internal static string Common_Position {
            get {
                return ResourceManager.GetString("Common_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set.
        /// </summary>
        internal static string Common_Set {
            get {
                return ResourceManager.GetString("Common_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Drag to change the value.
        /// </summary>
        internal static string Common_SliderDrag {
            get {
                return ResourceManager.GetString("Common_SliderDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Swap Width and Height.
        /// </summary>
        internal static string Common_SwapWidthHeight {
            get {
                return ResourceManager.GetString("Common_SwapWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Top.
        /// </summary>
        internal static string Common_Top {
            get {
                return ResourceManager.GetString("Common_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transform.
        /// </summary>
        internal static string Common_Transform {
            get {
                return ResourceManager.GetString("Common_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL.
        /// </summary>
        internal static string Common_Url {
            get {
                return ResourceManager.GetString("Common_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Width.
        /// </summary>
        internal static string Common_Width {
            get {
                return ResourceManager.GetString("Common_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a X.
        /// </summary>
        internal static string Common_X {
            get {
                return ResourceManager.GetString("Common_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Y.
        /// </summary>
        internal static string Common_Y {
            get {
                return ResourceManager.GetString("Common_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between -127 and 127.
        /// </summary>
        internal static string Contrast_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Contrast_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aspect Ratio.
        /// </summary>
        internal static string Crop_AspectRatio {
            get {
                return ResourceManager.GetString("Crop_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Aspect Ratio.
        /// </summary>
        internal static string Crop_AspectRatioToolTip {
            get {
                return ResourceManager.GetString("Crop_AspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crop.
        /// </summary>
        internal static string Crop_Button {
            get {
                return ResourceManager.GetString("Crop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crop Image.
        /// </summary>
        internal static string Crop_Title {
            get {
                return ResourceManager.GetString("Crop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color:.
        /// </summary>
        internal static string DrawCircle_Color {
            get {
                return ResourceManager.GetString("DrawCircle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Current color is {0}).
        /// </summary>
        internal static string DrawCircle_CurrentColorText {
            get {
                return ResourceManager.GetString("DrawCircle_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill Color:.
        /// </summary>
        internal static string DrawCircle_FillColor {
            get {
                return ResourceManager.GetString("DrawCircle_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line size:.
        /// </summary>
        internal static string DrawCircle_LineSize {
            get {
                return ResourceManager.GetString("DrawCircle_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set line size.
        /// </summary>
        internal static string DrawCircle_LineSizeToolTip {
            get {
                return ResourceManager.GetString("DrawCircle_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PickColor.
        /// </summary>
        internal static string DrawCircle_PickColor {
            get {
                return ResourceManager.GetString("DrawCircle_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Fill Color.
        /// </summary>
        internal static string DrawCircle_PickFillColor {
            get {
                return ResourceManager.GetString("DrawCircle_PickFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Circle.
        /// </summary>
        internal static string DrawCircle_Title {
            get {
                return ResourceManager.GetString("DrawCircle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color:.
        /// </summary>
        internal static string DrawRectangle_Color {
            get {
                return ResourceManager.GetString("DrawRectangle_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Current color is {0}).
        /// </summary>
        internal static string DrawRectangle_CurrentColorText {
            get {
                return ResourceManager.GetString("DrawRectangle_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill Color:.
        /// </summary>
        internal static string DrawRectangle_FillColor {
            get {
                return ResourceManager.GetString("DrawRectangle_FillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line size:.
        /// </summary>
        internal static string DrawRectangle_LineSize {
            get {
                return ResourceManager.GetString("DrawRectangle_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set line size.
        /// </summary>
        internal static string DrawRectangle_LineSizeToolTip {
            get {
                return ResourceManager.GetString("DrawRectangle_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PickColor.
        /// </summary>
        internal static string DrawRectangle_PickColor {
            get {
                return ResourceManager.GetString("DrawRectangle_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pick Fill Color.
        /// </summary>
        internal static string DrawRectangle_PickFillColor {
            get {
                return ResourceManager.GetString("DrawRectangle_PickFillColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Rectangle.
        /// </summary>
        internal static string DrawRectangle_Title {
            get {
                return ResourceManager.GetString("DrawRectangle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose image extension.
        /// </summary>
        internal static string Export_ChooseExtension {
            get {
                return ResourceManager.GetString("Export_ChooseExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Image.
        /// </summary>
        internal static string Export_ClientRadioText {
            get {
                return ResourceManager.GetString("Export_ClientRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Name.
        /// </summary>
        internal static string Export_FileNameLabel {
            get {
                return ResourceManager.GetString("Export_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter File Name.
        /// </summary>
        internal static string Export_FileNameToolTip {
            get {
                return ResourceManager.GetString("Export_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Image on Server.
        /// </summary>
        internal static string Export_ServerRadioText {
            get {
                return ResourceManager.GetString("Export_ServerRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Export Image.
        /// </summary>
        internal static string Export_Title {
            get {
                return ResourceManager.GetString("Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flip None.
        /// </summary>
        internal static string Flip_None {
            get {
                return ResourceManager.GetString("Flip_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Flip.
        /// </summary>
        internal static string Flip_Title {
            get {
                return ResourceManager.GetString("Flip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply.
        /// </summary>
        internal static string HueSaturation_ApplyBtn_Text {
            get {
                return ResourceManager.GetString("HueSaturation_ApplyBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apply the selected hue/saturation levels to the image.
        /// </summary>
        internal static string HueSaturation_ApplyBtn_ToolTip {
            get {
                return ResourceManager.GetString("HueSaturation_ApplyBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset.
        /// </summary>
        internal static string HueSaturation_ResetBtn_Text {
            get {
                return ResourceManager.GetString("HueSaturation_ResetBtn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reset the changes so far.
        /// </summary>
        internal static string HueSaturation_ResetBtn_ToolTip {
            get {
                return ResourceManager.GetString("HueSaturation_ResetBtn_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hue/Saturation.
        /// </summary>
        internal static string HueSaturation_Title {
            get {
                return ResourceManager.GetString("HueSaturation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between 0 and 360.
        /// </summary>
        internal static string Hue_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Hue_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Insert Image.
        /// </summary>
        internal static string InsertImage_Title {
            get {
                return ResourceManager.GetString("InsertImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a URL of an Image to Insert (example http://domain.com/img.png).
        /// </summary>
        internal static string InsertImage_UrlTxtToolTip {
            get {
                return ResourceManager.GetString("InsertImage_UrlTxtToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color:.
        /// </summary>
        internal static string Line_Color {
            get {
                return ResourceManager.GetString("Line_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Current color is {0}).
        /// </summary>
        internal static string Line_CurrentColorText {
            get {
                return ResourceManager.GetString("Line_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line size:.
        /// </summary>
        internal static string Line_LineSize {
            get {
                return ResourceManager.GetString("Line_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set line size.
        /// </summary>
        internal static string Line_LineSizeToolTip {
            get {
                return ResourceManager.GetString("Line_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PickColor.
        /// </summary>
        internal static string Line_PickColor {
            get {
                return ResourceManager.GetString("Line_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Draw Line.
        /// </summary>
        internal static string Line_Title {
            get {
                return ResourceManager.GetString("Line_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between 0 and 100%.
        /// </summary>
        internal static string Opacity_TextboxToolTip {
            get {
                return ResourceManager.GetString("Opacity_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Opacity.
        /// </summary>
        internal static string Opacity_Title {
            get {
                return ResourceManager.GetString("Opacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color:.
        /// </summary>
        internal static string Pencil_Color {
            get {
                return ResourceManager.GetString("Pencil_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (Current color is {0}).
        /// </summary>
        internal static string Pencil_CurrentColorText {
            get {
                return ResourceManager.GetString("Pencil_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Line size:.
        /// </summary>
        internal static string Pencil_LineSize {
            get {
                return ResourceManager.GetString("Pencil_LineSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set line size.
        /// </summary>
        internal static string Pencil_LineSizeToolTip {
            get {
                return ResourceManager.GetString("Pencil_LineSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PickColor.
        /// </summary>
        internal static string Pencil_PickColor {
            get {
                return ResourceManager.GetString("Pencil_PickColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pencil.
        /// </summary>
        internal static string Pencil_Title {
            get {
                return ResourceManager.GetString("Pencil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print.
        /// </summary>
        internal static string Print_Button {
            get {
                return ResourceManager.GetString("Print_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Print Image.
        /// </summary>
        internal static string Print_Title {
            get {
                return ResourceManager.GetString("Print_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please do not delete this string..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize.
        /// </summary>
        internal static string Resize_Button {
            get {
                return ResourceManager.GetString("Resize_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Percentage.
        /// </summary>
        internal static string Resize_Percentage {
            get {
                return ResourceManager.GetString("Resize_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Percentage of original Width x Height [0,100%].
        /// </summary>
        internal static string Resize_PercentageToolTip {
            get {
                return ResourceManager.GetString("Resize_PercentageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preset Sizes.
        /// </summary>
        internal static string Resize_PresetSizes {
            get {
                return ResourceManager.GetString("Resize_PresetSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select Preset Width x Height.
        /// </summary>
        internal static string Resize_PresetSizesToolTip {
            get {
                return ResourceManager.GetString("Resize_PresetSizesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize.
        /// </summary>
        internal static string Resize_Title {
            get {
                return ResourceManager.GetString("Resize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select a rotation angle.
        /// </summary>
        internal static string Rotate_DropDownToolTip {
            get {
                return ResourceManager.GetString("Rotate_DropDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rotate.
        /// </summary>
        internal static string Rotate_Title {
            get {
                return ResourceManager.GetString("Rotate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between -100 and 100.
        /// </summary>
        internal static string Saturation_TxtBoxToolTip {
            get {
                return ResourceManager.GetString("Saturation_TxtBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download Image.
        /// </summary>
        internal static string Save_ClientRadioText {
            get {
                return ResourceManager.GetString("Save_ClientRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Name.
        /// </summary>
        internal static string Save_FileNameLabel {
            get {
                return ResourceManager.GetString("Save_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter File Name.
        /// </summary>
        internal static string Save_FileNameToolTip {
            get {
                return ResourceManager.GetString("Save_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Image on Server.
        /// </summary>
        internal static string Save_ServerRadioText {
            get {
                return ResourceManager.GetString("Save_ServerRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Image.
        /// </summary>
        internal static string Save_Title {
            get {
                return ResourceManager.GetString("Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom to 100%.
        /// </summary>
        internal static string Zoom_ActualSizeToolTip {
            get {
                return ResourceManager.GetString("Zoom_ActualSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fit image in editable area.
        /// </summary>
        internal static string Zoom_BestFitToolTip {
            get {
                return ResourceManager.GetString("Zoom_BestFitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter a value between 0 and 100%.
        /// </summary>
        internal static string Zoom_TextboxToolTip {
            get {
                return ResourceManager.GetString("Zoom_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zoom.
        /// </summary>
        internal static string Zoom_Title {
            get {
                return ResourceManager.GetString("Zoom_Title", resourceCulture);
            }
        }
    }
}
