//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadScheduler {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadScheduler.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a All day.
        /// </summary>
        internal static string AdvancedAllDayEvent {
            get {
                return ResourceManager.GetString("AdvancedAllDayEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string AdvancedCalendarCancel {
            get {
                return ResourceManager.GetString("AdvancedCalendarCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string AdvancedCalendarOK {
            get {
                return ResourceManager.GetString("AdvancedCalendarOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Today.
        /// </summary>
        internal static string AdvancedCalendarToday {
            get {
                return ResourceManager.GetString("AdvancedCalendarToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close.
        /// </summary>
        internal static string AdvancedClose {
            get {
                return ResourceManager.GetString("AdvancedClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Daily.
        /// </summary>
        internal static string AdvancedDaily {
            get {
                return ResourceManager.GetString("AdvancedDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        internal static string AdvancedDay {
            get {
                return ResourceManager.GetString("AdvancedDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day(s).
        /// </summary>
        internal static string AdvancedDays {
            get {
                return ResourceManager.GetString("AdvancedDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        internal static string AdvancedDescription {
            get {
                return ResourceManager.GetString("AdvancedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Done.
        /// </summary>
        internal static string AdvancedDone {
            get {
                return ResourceManager.GetString("AdvancedDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Appointment.
        /// </summary>
        internal static string AdvancedEditAppointment {
            get {
                return ResourceManager.GetString("AdvancedEditAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End after.
        /// </summary>
        internal static string AdvancedEndAfter {
            get {
                return ResourceManager.GetString("AdvancedEndAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End by.
        /// </summary>
        internal static string AdvancedEndByThisDate {
            get {
                return ResourceManager.GetString("AdvancedEndByThisDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End date is required.
        /// </summary>
        internal static string AdvancedEndDateRequired {
            get {
                return ResourceManager.GetString("AdvancedEndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End time is required.
        /// </summary>
        internal static string AdvancedEndTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedEndTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Every.
        /// </summary>
        internal static string AdvancedEvery {
            get {
                return ResourceManager.GetString("AdvancedEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Every weekday.
        /// </summary>
        internal static string AdvancedEveryWeekday {
            get {
                return ResourceManager.GetString("AdvancedEveryWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a first.
        /// </summary>
        internal static string AdvancedFirst {
            get {
                return ResourceManager.GetString("AdvancedFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fourth.
        /// </summary>
        internal static string AdvancedFourth {
            get {
                return ResourceManager.GetString("AdvancedFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time.
        /// </summary>
        internal static string AdvancedFrom {
            get {
                return ResourceManager.GetString("AdvancedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hourly.
        /// </summary>
        internal static string AdvancedHourly {
            get {
                return ResourceManager.GetString("AdvancedHourly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour(s).
        /// </summary>
        internal static string AdvancedHours {
            get {
                return ResourceManager.GetString("AdvancedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invalid number.
        /// </summary>
        internal static string AdvancedInvalidNumber {
            get {
                return ResourceManager.GetString("AdvancedInvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a last.
        /// </summary>
        internal static string AdvancedLast {
            get {
                return ResourceManager.GetString("AdvancedLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day.
        /// </summary>
        internal static string AdvancedMaskDay {
            get {
                return ResourceManager.GetString("AdvancedMaskDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weekday.
        /// </summary>
        internal static string AdvancedMaskWeekday {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weekend day.
        /// </summary>
        internal static string AdvancedMaskWeekendDay {
            get {
                return ResourceManager.GetString("AdvancedMaskWeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Monthly.
        /// </summary>
        internal static string AdvancedMonthly {
            get {
                return ResourceManager.GetString("AdvancedMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a month(s).
        /// </summary>
        internal static string AdvancedMonths {
            get {
                return ResourceManager.GetString("AdvancedMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a More details.
        /// </summary>
        internal static string AdvancedMoreDetails {
            get {
                return ResourceManager.GetString("AdvancedMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Appointment.
        /// </summary>
        internal static string AdvancedNewAppointment {
            get {
                return ResourceManager.GetString("AdvancedNewAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No end date.
        /// </summary>
        internal static string AdvancedNoEndDate {
            get {
                return ResourceManager.GetString("AdvancedNoEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a occurrences.
        /// </summary>
        internal static string AdvancedOccurrences {
            get {
                return ResourceManager.GetString("AdvancedOccurrences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of.
        /// </summary>
        internal static string AdvancedOf {
            get {
                return ResourceManager.GetString("AdvancedOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a of every.
        /// </summary>
        internal static string AdvancedOfEvery {
            get {
                return ResourceManager.GetString("AdvancedOfEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Range of recurrence:.
        /// </summary>
        internal static string AdvancedRange {
            get {
                return ResourceManager.GetString("AdvancedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recur every.
        /// </summary>
        internal static string AdvancedRecurEvery {
            get {
                return ResourceManager.GetString("AdvancedRecurEvery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurrence.
        /// </summary>
        internal static string AdvancedRecurrence {
            get {
                return ResourceManager.GetString("AdvancedRecurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recurring task.
        /// </summary>
        internal static string AdvancedRecurringAppointment {
            get {
                return ResourceManager.GetString("AdvancedRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a reset exceptions.
        /// </summary>
        internal static string AdvancedReset {
            get {
                return ResourceManager.GetString("AdvancedReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a second.
        /// </summary>
        internal static string AdvancedSecond {
            get {
                return ResourceManager.GetString("AdvancedSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start date is required.
        /// </summary>
        internal static string AdvancedStartDateRequired {
            get {
                return ResourceManager.GetString("AdvancedStartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time must be before end time.
        /// </summary>
        internal static string AdvancedStartTimeBeforeEndTime {
            get {
                return ResourceManager.GetString("AdvancedStartTimeBeforeEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start time is required.
        /// </summary>
        internal static string AdvancedStartTimeRequired {
            get {
                return ResourceManager.GetString("AdvancedStartTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subject.
        /// </summary>
        internal static string AdvancedSubject {
            get {
                return ResourceManager.GetString("AdvancedSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please provide appointment subject.
        /// </summary>
        internal static string AdvancedSubjectRequired {
            get {
                return ResourceManager.GetString("AdvancedSubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The.
        /// </summary>
        internal static string AdvancedThe {
            get {
                return ResourceManager.GetString("AdvancedThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a third.
        /// </summary>
        internal static string AdvancedThird {
            get {
                return ResourceManager.GetString("AdvancedThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time zone.
        /// </summary>
        internal static string AdvancedTimeZone {
            get {
                return ResourceManager.GetString("AdvancedTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End time.
        /// </summary>
        internal static string AdvancedTo {
            get {
                return ResourceManager.GetString("AdvancedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Weekly.
        /// </summary>
        internal static string AdvancedWeekly {
            get {
                return ResourceManager.GetString("AdvancedWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a week(s) on.
        /// </summary>
        internal static string AdvancedWeeks {
            get {
                return ResourceManager.GetString("AdvancedWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Working....
        /// </summary>
        internal static string AdvancedWorking {
            get {
                return ResourceManager.GetString("AdvancedWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yearly.
        /// </summary>
        internal static string AdvancedYearly {
            get {
                return ResourceManager.GetString("AdvancedYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a all day.
        /// </summary>
        internal static string AllDay {
            get {
                return ResourceManager.GetString("AllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string ConfirmCancel {
            get {
                return ResourceManager.GetString("ConfirmCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to delete this appointment?.
        /// </summary>
        internal static string ConfirmDeleteText {
            get {
                return ResourceManager.GetString("ConfirmDeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm delete.
        /// </summary>
        internal static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        internal static string ConfirmOK {
            get {
                return ResourceManager.GetString("ConfirmOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceDeleteOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete the series..
        /// </summary>
        internal static string ConfirmRecurrenceDeleteSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Deleting a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceEditOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit the series..
        /// </summary>
        internal static string ConfirmRecurrenceEditSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editing a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceEditTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceMoveOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Move the series..
        /// </summary>
        internal static string ConfirmRecurrenceMoveSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Moving a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceMoveTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceMoveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize only this occurrence..
        /// </summary>
        internal static string ConfirmRecurrenceResizeOccurrence {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resize the series..
        /// </summary>
        internal static string ConfirmRecurrenceResizeSeries {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resizing a recurring appointment.
        /// </summary>
        internal static string ConfirmRecurrenceResizeTitle {
            get {
                return ResourceManager.GetString("ConfirmRecurrenceResizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to delete all existing recurrence exceptions?.
        /// </summary>
        internal static string ConfirmResetExceptionsText {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm reset exceptions.
        /// </summary>
        internal static string ConfirmResetExceptionsTitle {
            get {
                return ResourceManager.GetString("ConfirmResetExceptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Appointment.
        /// </summary>
        internal static string ContextMenuAddAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Recurring Appointment.
        /// </summary>
        internal static string ContextMenuAddRecurringAppointment {
            get {
                return ResourceManager.GetString("ContextMenuAddRecurringAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        internal static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit.
        /// </summary>
        internal static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go to today.
        /// </summary>
        internal static string ContextMenuGoToToday {
            get {
                return ResourceManager.GetString("ContextMenuGoToToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Day.
        /// </summary>
        internal static string HeaderDay {
            get {
                return ResourceManager.GetString("HeaderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Month.
        /// </summary>
        internal static string HeaderMonth {
            get {
                return ResourceManager.GetString("HeaderMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Multi-day.
        /// </summary>
        internal static string HeaderMultiDay {
            get {
                return ResourceManager.GetString("HeaderMultiDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a next day.
        /// </summary>
        internal static string HeaderNextDay {
            get {
                return ResourceManager.GetString("HeaderNextDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a previous day.
        /// </summary>
        internal static string HeaderPrevDay {
            get {
                return ResourceManager.GetString("HeaderPrevDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Timeline.
        /// </summary>
        internal static string HeaderTimeline {
            get {
                return ResourceManager.GetString("HeaderTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a today.
        /// </summary>
        internal static string HeaderToday {
            get {
                return ResourceManager.GetString("HeaderToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Week.
        /// </summary>
        internal static string HeaderWeek {
            get {
                return ResourceManager.GetString("HeaderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reminder.
        /// </summary>
        internal static string Reminder {
            get {
                return ResourceManager.GetString("Reminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a before start.
        /// </summary>
        internal static string ReminderBeforeStart {
            get {
                return ResourceManager.GetString("ReminderBeforeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a day.
        /// </summary>
        internal static string ReminderDay {
            get {
                return ResourceManager.GetString("ReminderDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a days.
        /// </summary>
        internal static string ReminderDays {
            get {
                return ResourceManager.GetString("ReminderDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dismiss.
        /// </summary>
        internal static string ReminderDismiss {
            get {
                return ResourceManager.GetString("ReminderDismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dismiss All.
        /// </summary>
        internal static string ReminderDismissAll {
            get {
                return ResourceManager.GetString("ReminderDismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a due in.
        /// </summary>
        internal static string ReminderDueIn {
            get {
                return ResourceManager.GetString("ReminderDueIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hour.
        /// </summary>
        internal static string ReminderHour {
            get {
                return ResourceManager.GetString("ReminderHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hours.
        /// </summary>
        internal static string ReminderHours {
            get {
                return ResourceManager.GetString("ReminderHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minute.
        /// </summary>
        internal static string ReminderMinute {
            get {
                return ResourceManager.GetString("ReminderMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a minutes.
        /// </summary>
        internal static string ReminderMinutes {
            get {
                return ResourceManager.GetString("ReminderMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a None.
        /// </summary>
        internal static string ReminderNone {
            get {
                return ResourceManager.GetString("ReminderNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Item.
        /// </summary>
        internal static string ReminderOpenItem {
            get {
                return ResourceManager.GetString("ReminderOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a overdue.
        /// </summary>
        internal static string ReminderOverdue {
            get {
                return ResourceManager.GetString("ReminderOverdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reminders.
        /// </summary>
        internal static string Reminders {
            get {
                return ResourceManager.GetString("Reminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Snooze.
        /// </summary>
        internal static string ReminderSnooze {
            get {
                return ResourceManager.GetString("ReminderSnooze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click Snooze to be reminded again in:.
        /// </summary>
        internal static string ReminderSnoozeHint {
            get {
                return ResourceManager.GetString("ReminderSnoozeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a week.
        /// </summary>
        internal static string ReminderWeek {
            get {
                return ResourceManager.GetString("ReminderWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a weeks.
        /// </summary>
        internal static string ReminderWeeks {
            get {
                return ResourceManager.GetString("ReminderWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please do not remove this key..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show 24 hours....
        /// </summary>
        internal static string Show24Hours {
            get {
                return ResourceManager.GetString("Show24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Options.
        /// </summary>
        internal static string ShowAdvancedForm {
            get {
                return ResourceManager.GetString("ShowAdvancedForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show business hours....
        /// </summary>
        internal static string ShowBusinessHours {
            get {
                return ResourceManager.GetString("ShowBusinessHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a more....
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
    }
}
