//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesLocal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesLocal() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResourcesLocal", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string BllImportacionexcelImportNew {
            get {
                return ResourceManager.GetString("BllImportacionexcelImportNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizado.
        /// </summary>
        internal static string BllImportacionexcelImportUpdated {
            get {
                return ResourceManager.GetString("BllImportacionexcelImportUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del campo direccion nombre es demasiado grande (maximo 250).
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessNameLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se debe definir la direccion si se define el tipo.
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessNameNull {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El numero de la direccion solo puede contener caracteres numericos.
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessNumeric {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del campo direccion otro es demasiado grande (maximo 50).
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessOtherLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessOtherLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo de direccion no existe.
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessType {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si se define la direccion se debe definir el tipo.
        /// </summary>
        internal static string BllImportacionexcelValidateAdreessTypeNull {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateAdreessTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Unidad de Negocio.
        /// </summary>
        internal static string BllImportacionexcelValidateBusinessUnit {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Cargos.
        /// </summary>
        internal static string BllImportacionexcelValidateCharges {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateCharges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró Cargos.
        /// </summary>
        internal static string BllImportacionexcelValidateChargesValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateChargesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Tipo de Contrato.
        /// </summary>
        internal static string BllImportacionexcelValidateContractType {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró Tipo de Contrato.
        /// </summary>
        internal static string BllImportacionexcelValidateContractTypeValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateContractTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Fecha de Contrato.
        /// </summary>
        internal static string BllImportacionexcelValidateDate {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado en Fecha de Contrato no es una fecha válida.
        /// </summary>
        internal static string BllImportacionexcelValidateDateValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateDateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Nivel de Escolaridad SENCE.
        /// </summary>
        internal static string BllImportacionexcelValidateEducationalLevel {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateEducationalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró Nivel de Escolaridad SENCE.
        /// </summary>
        internal static string BllImportacionexcelValidateEducationalLevelValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateEducationalLevelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Email.
        /// </summary>
        internal static string BllImportacionexcelValidateEmail {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del correo electronico es demasiado grande.
        /// </summary>
        internal static string BllImportacionexcelValidateEmailLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado para Email no es válido.
        /// </summary>
        internal static string BllImportacionexcelValidateEmailValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateEmailValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Franquicia SENCE.
        /// </summary>
        internal static string BllImportacionexcelValidateFranchise {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateFranchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado en Franquicia SENCE no es númerico.
        /// </summary>
        internal static string BllImportacionexcelValidateFranchiseNoNumeric {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateFranchiseNoNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado en Franquicia SENCE no esta en los rangos permitidos.
        /// </summary>
        internal static string BllImportacionexcelValidateFranchiseNoRange {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateFranchiseNoRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Rut Sociedad.
        /// </summary>
        internal static string BllImportacionexcelValidateIdentityCompany {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateIdentityCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado para RUT Sociedad no es válido.
        /// </summary>
        internal static string BllImportacionexcelValidateIdentityCompanyValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateIdentityCompanyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Rut de Jefatura.
        /// </summary>
        internal static string BllImportacionexcelValidateLeadershipIdentity {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateLeadershipIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado para RUT Jefatura no es válido.
        /// </summary>
        internal static string BllImportacionexcelValidateLeadershipIdentityValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateLeadershipIdentityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El  RUT Jefatura no se encuentra Registrado.
        /// </summary>
        internal static string BllImportacionexcelValidateLeadershipIdentityValueNoExists {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateLeadershipIdentityValueNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Ubicación.
        /// </summary>
        internal static string BllImportacionexcelValidateLocation {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Apellido Materno.
        /// </summary>
        internal static string BllImportacionexcelValidateMaternalSurname {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateMaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del apellido materno es demasiado grande.
        /// </summary>
        internal static string BllImportacionexcelValidateMaternalSurnameLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateMaternalSurnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Nombre.
        /// </summary>
        internal static string BllImportacionexcelValidateName {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del nombre es demasiado grande.
        /// </summary>
        internal static string BllImportacionexcelValidateNameLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sociedad contratante no existe con el rut.
        /// </summary>
        internal static string BllImportacionexcelValidateNoCompanyValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateNoCompanyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sociedad no es de tipo contratante para la sociedad actual.
        /// </summary>
        internal static string BllImportacionexcelValidateNoCompanyValueType {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateNoCompanyValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Nivel Ocupacional SENCE.
        /// </summary>
        internal static string BllImportacionexcelValidateOccupationalLevel {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateOccupationalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró Nivel Ocupacional SENCE.
        /// </summary>
        internal static string BllImportacionexcelValidateOccupationalLevelValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateOccupationalLevelValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Unidad Organizacional.
        /// </summary>
        internal static string BllImportacionexcelValidateOrganizationalUnit {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateOrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontró Unidad Organizacional.
        /// </summary>
        internal static string BllImportacionexcelValidateOrganizationalUnitValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateOrganizationalUnitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Apellido Paterno.
        /// </summary>
        internal static string BllImportacionexcelValidatePaternalSurname {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidatePaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del apellido paterno es demasiado grande.
        /// </summary>
        internal static string BllImportacionexcelValidatePaternalSurnameLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidatePaternalSurnameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado Fono.
        /// </summary>
        internal static string BllImportacionexcelValidatePhone {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidatePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cantidad de caracteres del telefono es demasiado grande.
        /// </summary>
        internal static string BllImportacionexcelValidatePhoneLength {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidatePhoneLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha especificado RUT.
        /// </summary>
        internal static string BllImportacionexcelValidateRut {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El valor especificado para RUT no es válido.
        /// </summary>
        internal static string BllImportacionexcelValidateRutValue {
            get {
                return ResourceManager.GetString("BllImportacionexcelValidateRutValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin información.
        /// </summary>
        internal static string ConstantNoInformation {
            get {
                return ResourceManager.GetString("ConstantNoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Emal.
        /// </summary>
        internal static string ContractEmail {
            get {
                return ResourceManager.GetString("ContractEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut Sociedad Contratante.
        /// </summary>
        internal static string ContractIdentificationContractingCompany {
            get {
                return ResourceManager.GetString("ContractIdentificationContractingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Telefono.
        /// </summary>
        internal static string ContractPhone {
            get {
                return ResourceManager.GetString("ContractPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo.
        /// </summary>
        internal static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se a especificado el archivo.
        /// </summary>
        internal static string DialogDocumentosNoFile {
            get {
                return ResourceManager.GetString("DialogDocumentosNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Búsqueda Avanzada.
        /// </summary>
        internal static string DockAdvancedSearchCommandText {
            get {
                return ResourceManager.GetString("DockAdvancedSearchCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        internal static string DockCloseCommandText {
            get {
                return ResourceManager.GetString("DockCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar externo.
        /// </summary>
        internal static string DockCommandAgregarExterno {
            get {
                return ResourceManager.GetString("DockCommandAgregarExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clonar Evento.
        /// </summary>
        internal static string DockDuplicateCommand {
            get {
                return ResourceManager.GetString("DockDuplicateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar.
        /// </summary>
        internal static string DockNewCommandText {
            get {
                return ResourceManager.GetString("DockNewCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver página que indique en la fuente.
        /// </summary>
        internal static string DockNewReturn {
            get {
                return ResourceManager.GetString("DockNewReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imprimir.
        /// </summary>
        internal static string DockPrintCommandText {
            get {
                return ResourceManager.GetString("DockPrintCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volver.
        /// </summary>
        internal static string DockReturnCommand {
            get {
                return ResourceManager.GetString("DockReturnCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        internal static string DockSaveCommandText {
            get {
                return ResourceManager.GetString("DockSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desvincular.
        /// </summary>
        internal static string DockUnlinkCommandText {
            get {
                return ResourceManager.GetString("DockUnlinkCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No Vigente.
        /// </summary>
        internal static string EstadoContratoNoVigente {
            get {
                return ResourceManager.GetString("EstadoContratoNoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Vigente.
        /// </summary>
        internal static string EstadoContratoVigente {
            get {
                return ResourceManager.GetString("EstadoContratoVigente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        internal static string EstadoPersonaNuevo {
            get {
                return ResourceManager.GetString("EstadoPersonaNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No definido.
        /// </summary>
        internal static string GridUndefined {
            get {
                return ResourceManager.GetString("GridUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Negocio.
        /// </summary>
        internal static string JobPositionBusinessUnit {
            get {
                return ResourceManager.GetString("JobPositionBusinessUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Franquicia SENSE.
        /// </summary>
        internal static string JobPositionFranchise {
            get {
                return ResourceManager.GetString("JobPositionFranchise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut Jefatura.
        /// </summary>
        internal static string JobPositionLeadershipIdentification {
            get {
                return ResourceManager.GetString("JobPositionLeadershipIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicacion.
        /// </summary>
        internal static string JobPositionLocation {
            get {
                return ResourceManager.GetString("JobPositionLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel ocupacional SENCE.
        /// </summary>
        internal static string JobPositionOccupationalLevel {
            get {
                return ResourceManager.GetString("JobPositionOccupationalLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidad Organizacional.
        /// </summary>
        internal static string JobPositionOrganizationalUnit {
            get {
                return ResourceManager.GetString("JobPositionOrganizationalUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string JobPositionPosition {
            get {
                return ResourceManager.GetString("JobPositionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escolaridad SENSE.
        /// </summary>
        internal static string JobPositionSchooling {
            get {
                return ResourceManager.GetString("JobPositionSchooling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver.
        /// </summary>
        internal static string LinkVerDocumento {
            get {
                return ResourceManager.GetString("LinkVerDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a revision: {0}.
        /// </summary>
        internal static string LoginRevision {
            get {
                return ResourceManager.GetString("LoginRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se Grabaron los Datos Correctamente.
        /// </summary>
        internal static string Mensaje_1 {
            get {
                return ResourceManager.GetString("Mensaje_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Actualizados.
        /// </summary>
        internal static string Mensaje_2 {
            get {
                return ResourceManager.GetString("Mensaje_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo ha sido enviado satisfactoriamente.
        /// </summary>
        internal static string NotificacionCorrectoEnvioCorreo {
            get {
                return ResourceManager.GetString("NotificacionCorrectoEnvioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al enviar correo al destinatario.
        /// </summary>
        internal static string NotificacionFalloEnvioCorreo {
            get {
                return ResourceManager.GetString("NotificacionFalloEnvioCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a warning.
        /// </summary>
        internal static string NotificationDefaultExceptionContentIcon {
            get {
                return ResourceManager.GetString("NotificationDefaultExceptionContentIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a none.
        /// </summary>
        internal static string NotificationDefaultExceptionIcon {
            get {
                return ResourceManager.GetString("NotificationDefaultExceptionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reinténtelo nuevamente.
        /// </summary>
        internal static string NotificationDefaultExceptionText {
            get {
                return ResourceManager.GetString("NotificationDefaultExceptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El registro se ha Guardado Correctamente.
        /// </summary>
        internal static string NotificationDefaultSaveText {
            get {
                return ResourceManager.GetString("NotificationDefaultSaveText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Digital Learning.
        /// </summary>
        internal static string NotificationDefaultTitle {
            get {
                return ResourceManager.GetString("NotificationDefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este identificador no es válido, por favor vuelva a ingresarlo..
        /// </summary>
        internal static string NotificationInvalidRut {
            get {
                return ResourceManager.GetString("NotificationInvalidRut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del evento es distinto al del Catalogo..
        /// </summary>
        internal static string NotificationNombreDistintoEvento {
            get {
                return ResourceManager.GetString("NotificationNombreDistintoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del evento es distinto al del SENCE..
        /// </summary>
        internal static string NotificationNombreDistintoSENCE {
            get {
                return ResourceManager.GetString("NotificationNombreDistintoSENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede desvincular este contrato.
        /// </summary>
        internal static string NotificationNoUnlink {
            get {
                return ResourceManager.GetString("NotificationNoUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento guardado Correctamente.
        /// </summary>
        internal static string NotificationSaveDocument {
            get {
                return ResourceManager.GetString("NotificationSaveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin Cambios.
        /// </summary>
        internal static string NotificationSaveUnchanged {
            get {
                return ResourceManager.GetString("NotificationSaveUnchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desvinculación exitosa.
        /// </summary>
        internal static string NotificationUnlink {
            get {
                return ResourceManager.GetString("NotificationUnlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no esta Registrado.
        /// </summary>
        internal static string NotificationUsuarioNoRegistrado {
            get {
                return ResourceManager.GetString("NotificationUsuarioNoRegistrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario sin correo eléctronico informado.
        /// </summary>
        internal static string NotificationUsuarioSinCorreo {
            get {
                return ResourceManager.GetString("NotificationUsuarioSinCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rut.
        /// </summary>
        internal static string PeopleIdentification {
            get {
                return ResourceManager.GetString("PeopleIdentification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno.
        /// </summary>
        internal static string PeopleMaternalSurname {
            get {
                return ResourceManager.GetString("PeopleMaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string PeopleName {
            get {
                return ResourceManager.GetString("PeopleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        internal static string PeoplePaternalSurname {
            get {
                return ResourceManager.GetString("PeoplePaternalSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string RadAsyncUploadCancel {
            get {
                return ResourceManager.GetString("RadAsyncUploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remover.
        /// </summary>
        internal static string RadAsyncUploadRemove {
            get {
                return ResourceManager.GetString("RadAsyncUploadRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccionar.
        /// </summary>
        internal static string RadAsyncUploadSelect {
            get {
                return ResourceManager.GetString("RadAsyncUploadSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todas....
        /// </summary>
        internal static string RadComboTextBusquedaTodas {
            get {
                return ResourceManager.GetString("RadComboTextBusquedaTodas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capacitaciones.
        /// </summary>
        internal static string RadDockCapacitacionGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockCapacitacionGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargo.
        /// </summary>
        internal static string RadDockCargoGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockCargoGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Certificaciones Requeridas.
        /// </summary>
        internal static string RadDockCertificacionGrilla {
            get {
                return ResourceManager.GetString("RadDockCertificacionGrilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clientes.
        /// </summary>
        internal static string RadDockClientesGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockClientesGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente/Software.
        /// </summary>
        internal static string RadDockClienteSoftwareGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockClienteSoftwareGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Software Modulo.
        /// </summary>
        internal static string RadDockClienteSoftwareModuloGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockClienteSoftwareModuloGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente Software Users.
        /// </summary>
        internal static string RadDockClienteSoftwareUsersGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockClienteSoftwareUsersGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cliente/Usuarios.
        /// </summary>
        internal static string RadDockClienteUsersGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockClienteUsersGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Conducta Competencia.
        /// </summary>
        internal static string RadDockConductaGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockConductaGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contratos.
        /// </summary>
        internal static string RadDockContratoGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockContratoGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Detalle Perfil.
        /// </summary>
        internal static string RadDockDetallePerfilGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockDetallePerfilGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia de Cargo.
        /// </summary>
        internal static string RadDockFamiliaCargoGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockFamiliaCargoGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Familia Competencia.
        /// </summary>
        internal static string RadDockFamiliaCompetenciaGrillaAdd {
            get {
                return ResourceManager.GetString("RadDockFamiliaCompetenciaGrillaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita Familia Competencia.
        /// </summary>
        internal static string RadDockFamiliaCompetenciaGrillaEdit {
            get {
                return ResourceManager.GetString("RadDockFamiliaCompetenciaGrillaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia Competencia.
        /// </summary>
        internal static string RadDockFamiliaCompetenciaGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockFamiliaCompetenciaGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información Básica.
        /// </summary>
        internal static string RadDockFormularioInformacionBasicaTitle {
            get {
                return ResourceManager.GetString("RadDockFormularioInformacionBasicaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcionalidades.
        /// </summary>
        internal static string RadDockFuncionalidadesGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockFuncionalidadesGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funciones.
        /// </summary>
        internal static string RadDockFuncionesGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockFuncionesGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Graduación.
        /// </summary>
        internal static string RadDockGraduacionesGrillaAdd {
            get {
                return ResourceManager.GetString("RadDockGraduacionesGrillaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita Graduación.
        /// </summary>
        internal static string RadDockGraduacionesGrillaEdit {
            get {
                return ResourceManager.GetString("RadDockGraduacionesGrillaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Graduación.
        /// </summary>
        internal static string RadDockGraduacionGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockGraduacionGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Habilidades.
        /// </summary>
        internal static string RadDockHabilidadesGrillaAdd {
            get {
                return ResourceManager.GetString("RadDockHabilidadesGrillaAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Habilidades.
        /// </summary>
        internal static string RadDockHabilidadesGrillaEdit {
            get {
                return ResourceManager.GetString("RadDockHabilidadesGrillaEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Habilidades.
        /// </summary>
        internal static string RadDockHabilidadesGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockHabilidadesGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar Asistencia.
        /// </summary>
        internal static string RadDockImport {
            get {
                return ResourceManager.GetString("RadDockImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Items.
        /// </summary>
        internal static string RadDockItemsGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockItemsGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jornada Laboral.
        /// </summary>
        internal static string RadDockJornadaLaboralGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockJornadaLaboralGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modulos.
        /// </summary>
        internal static string RadDockModulosGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockModulosGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel de Idiomas Requerido.
        /// </summary>
        internal static string RadDockNivelIdiomaHabilidadesCargo {
            get {
                return ResourceManager.GetString("RadDockNivelIdiomaHabilidadesCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paginas.
        /// </summary>
        internal static string RadDockPaginasGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockPaginasGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        internal static string RadDockPerfilGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockPerfilGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad.
        /// </summary>
        internal static string RadDockSociedadGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockSociedadGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software.
        /// </summary>
        internal static string RadDockSoftwareGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockSoftwareGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Software/Modulo.
        /// </summary>
        internal static string RadDockSoftwareModuloGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockSoftwareModuloGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de Competencias.
        /// </summary>
        internal static string RadDockTipoCompetenciaGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockTipoCompetenciaGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades de Negocio.
        /// </summary>
        internal static string RadDockUnidadesNegocioGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockUnidadesNegocioGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unidades Organizacionales.
        /// </summary>
        internal static string RadDockUnidadesOrganizacionalGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockUnidadesOrganizacionalGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        internal static string RadDockUsuarioGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockUsuarioGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario Perfil.
        /// </summary>
        internal static string RadDockUsuarioPerfilGrillaTitle {
            get {
                return ResourceManager.GetString("RadDockUsuarioPerfilGrillaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Contrato.
        /// </summary>
        internal static string RadGridContratoHeaderFechaContrato {
            get {
                return ResourceManager.GetString("RadGridContratoHeaderFechaContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha Término.
        /// </summary>
        internal static string RadGridContratoHeaderFechaTermino {
            get {
                return ResourceManager.GetString("RadGridContratoHeaderFechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad Mandante.
        /// </summary>
        internal static string RadGridContratoHeaderSociedadMandante {
            get {
                return ResourceManager.GetString("RadGridContratoHeaderSociedadMandante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Contrato.
        /// </summary>
        internal static string RadGridContratoHeaderTipoContrato {
            get {
                return ResourceManager.GetString("RadGridContratoHeaderTipoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registro de contratos.
        /// </summary>
        internal static string RadGridContratoNoRecords {
            get {
                return ResourceManager.GetString("RadGridContratoNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay registros para mostrar.
        /// </summary>
        internal static string RadGridNoRecords {
            get {
                return ResourceManager.GetString("RadGridNoRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Columna Excel.
        /// </summary>
        internal static string TabConfirmationGridHeaderColumnExcel {
            get {
                return ResourceManager.GetString("TabConfirmationGridHeaderColumnExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dato.
        /// </summary>
        internal static string TabConfirmationGridHeaderData {
            get {
                return ResourceManager.GetString("TabConfirmationGridHeaderData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        internal static string TabConfirmationGridHeaderSection {
            get {
                return ResourceManager.GetString("TabConfirmationGridHeaderSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sociedad Contratante Predeterminada.
        /// </summary>
        internal static string TabLoadDefaultContractingCompany {
            get {
                return ResourceManager.GetString("TabLoadDefaultContractingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Formato no válido: La extensión del archivo debe ser .xls, .xlsx, .csv.
        /// </summary>
        internal static string TabLoadExtentionError {
            get {
                return ResourceManager.GetString("TabLoadExtentionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        internal static string TabLoadFile {
            get {
                return ResourceManager.GetString("TabLoadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe especificar un archivo.
        /// </summary>
        internal static string TabLoadMustSpecifyFile {
            get {
                return ResourceManager.GetString("TabLoadMustSpecifyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contrato.
        /// </summary>
        internal static string TabMappingContract {
            get {
                return ResourceManager.GetString("TabMappingContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Posición laboral.
        /// </summary>
        internal static string TabMappingJobPosition {
            get {
                return ResourceManager.GetString("TabMappingJobPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personas.
        /// </summary>
        internal static string TabMappingPeople {
            get {
                return ResourceManager.GetString("TabMappingPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se a terminado de importar los registros.
        /// </summary>
        internal static string TabRegisterAlertFinish {
            get {
                return ResourceManager.GetString("TabRegisterAlertFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro de eventos.
        /// </summary>
        internal static string TabRegisterEventLog {
            get {
                return ResourceManager.GetString("TabRegisterEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string TabRegisterEventLogClear {
            get {
                return ResourceManager.GetString("TabRegisterEventLogClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevos : .
        /// </summary>
        internal static string TabRegisterNew {
            get {
                return ResourceManager.GetString("TabRegisterNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizados :.
        /// </summary>
        internal static string TabRegisterUpdated {
            get {
                return ResourceManager.GetString("TabRegisterUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido.
        /// </summary>
        internal static string TabValidateGridContent {
            get {
                return ResourceManager.GetString("TabValidateGridContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo (E=Error, A=Advertencia).
        /// </summary>
        internal static string TabValidateGridEventType {
            get {
                return ResourceManager.GetString("TabValidateGridEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo.
        /// </summary>
        internal static string TabValidateGridField {
            get {
                return ResourceManager.GetString("TabValidateGridField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mensaje.
        /// </summary>
        internal static string TabValidateGridMessage {
            get {
                return ResourceManager.GetString("TabValidateGridMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fila.
        /// </summary>
        internal static string TabValidateGridRow {
            get {
                return ResourceManager.GetString("TabValidateGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} registros importados de {1}.
        /// </summary>
        internal static string TextImportedRecords {
            get {
                return ResourceManager.GetString("TextImportedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se detectaron errores en la validación de los datos. No se podrá realizar la importación hasta corregirlos..
        /// </summary>
        internal static string TextImportValidationErrors {
            get {
                return ResourceManager.GetString("TextImportValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver solo errores que impiden la importación de datos.
        /// </summary>
        internal static string TextShowOnlyValidationErrors {
            get {
                return ResourceManager.GetString("TextShowOnlyValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmación.
        /// </summary>
        internal static string TextTabConfirm {
            get {
                return ResourceManager.GetString("TextTabConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carga.
        /// </summary>
        internal static string TextTabLoad {
            get {
                return ResourceManager.GetString("TextTabLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        internal static string TextTabLog {
            get {
                return ResourceManager.GetString("TextTabLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mapeo.
        /// </summary>
        internal static string TextTabMap {
            get {
                return ResourceManager.GetString("TextTabMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        internal static string TextTabValidate {
            get {
                return ResourceManager.GetString("TextTabValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} registros validados de {1}.
        /// </summary>
        internal static string TextValidatedRecords {
            get {
                return ResourceManager.GetString("TextValidatedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comuna.
        /// </summary>
        internal static string TituloBuscarComuna {
            get {
                return ResourceManager.GetString("TituloBuscarComuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Región.
        /// </summary>
        internal static string TituloBuscarRegion {
            get {
                return ResourceManager.GetString("TituloBuscarRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Ubicaciones.
        /// </summary>
        internal static string TituloBuscarUbicacion {
            get {
                return ResourceManager.GetString("TituloBuscarUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Calendario del Evento.
        /// </summary>
        internal static string TituloCalendario {
            get {
                return ResourceManager.GetString("TituloCalendario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar o Agregar competencias conductuales desde el catálogo.
        /// </summary>
        internal static string TituloCompetenciasConductualesAdd {
            get {
                return ResourceManager.GetString("TituloCompetenciasConductualesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Competencias Conductuales .
        /// </summary>
        internal static string TituloCompetenciasConductualesEdit {
            get {
                return ResourceManager.GetString("TituloCompetenciasConductualesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva competencia técnica para el cargo.
        /// </summary>
        internal static string TituloCompetenciasTecnicasAdd {
            get {
                return ResourceManager.GetString("TituloCompetenciasTecnicasAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Competencias Técnicas.
        /// </summary>
        internal static string TituloCompetenciasTecnicasEdit {
            get {
                return ResourceManager.GetString("TituloCompetenciasTecnicasEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costos del Evento.
        /// </summary>
        internal static string TituloCostoEvento {
            get {
                return ResourceManager.GetString("TituloCostoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Evento.
        /// </summary>
        internal static string TituloDatosEvento {
            get {
                return ResourceManager.GetString("TituloDatosEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Corresponde a las certificaciones o acreditaciones definidas a nivel corporativo.
        /// </summary>
        internal static string Titulodescripcioncertificacion {
            get {
                return ResourceManager.GetString("Titulodescripcioncertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desvincular Contrato Seleccionado.
        /// </summary>
        internal static string TituloDesvincularContrato {
            get {
                return ResourceManager.GetString("TituloDesvincularContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando {0}.
        /// </summary>
        internal static string TituloEditAbstractTableEditor {
            get {
                return ResourceManager.GetString("TituloEditAbstractTableEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando registro de activo.
        /// </summary>
        internal static string TituloEditarActivo {
            get {
                return ResourceManager.GetString("TituloEditarActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Antecedente de Salud Ocupacional.
        /// </summary>
        internal static string TituloEditarAntecedenteSalud {
            get {
                return ResourceManager.GetString("TituloEditarAntecedenteSalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Capacitación Seleccionada.
        /// </summary>
        internal static string TituloEditarCapacitacion {
            get {
                return ResourceManager.GetString("TituloEditarCapacitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cargo.
        /// </summary>
        internal static string TituloEditarCargo {
            get {
                return ResourceManager.GetString("TituloEditarCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Certificación.
        /// </summary>
        internal static string TituloEditarCertificacionHabilidadesCargo {
            get {
                return ResourceManager.GetString("TituloEditarCertificacionHabilidadesCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Clientes.
        /// </summary>
        internal static string TituloEditarCliente {
            get {
                return ResourceManager.GetString("TituloEditarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cliente Software.
        /// </summary>
        internal static string TituloEditarClienteSoftware {
            get {
                return ResourceManager.GetString("TituloEditarClienteSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cliente Software Modulo.
        /// </summary>
        internal static string TituloEditarClienteSoftwareModulo {
            get {
                return ResourceManager.GetString("TituloEditarClienteSoftwareModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cliente Software Users.
        /// </summary>
        internal static string TituloEditarClienteSoftwareUsers {
            get {
                return ResourceManager.GetString("TituloEditarClienteSoftwareUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Cliente/Usuarios.
        /// </summary>
        internal static string TituloEditarClienteUsers {
            get {
                return ResourceManager.GetString("TituloEditarClienteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando comentario.
        /// </summary>
        internal static string TituloEditarComentario {
            get {
                return ResourceManager.GetString("TituloEditarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Contrato Seleccionado.
        /// </summary>
        internal static string TituloEditarContrato {
            get {
                return ResourceManager.GetString("TituloEditarContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando resultado de procesos de evaluación del desempeño seleccionado.
        /// </summary>
        internal static string TituloEditarDesempeno {
            get {
                return ResourceManager.GetString("TituloEditarDesempeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando documento.
        /// </summary>
        internal static string TituloEditarDocumento {
            get {
                return ResourceManager.GetString("TituloEditarDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita Familia Cargo.
        /// </summary>
        internal static string TituloEditarFamiliaCargo {
            get {
                return ResourceManager.GetString("TituloEditarFamiliaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edita Familia Competencia.
        /// </summary>
        internal static string TituloEditarFamiliaCompetencia {
            get {
                return ResourceManager.GetString("TituloEditarFamiliaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Función.
        /// </summary>
        internal static string TituloEditarFuncion {
            get {
                return ResourceManager.GetString("TituloEditarFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Funcionalidad.
        /// </summary>
        internal static string TituloEditarFuncionalidades {
            get {
                return ResourceManager.GetString("TituloEditarFuncionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Graduación.
        /// </summary>
        internal static string TituloEditarGraduacion {
            get {
                return ResourceManager.GetString("TituloEditarGraduacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Graduación.
        /// </summary>
        internal static string TituloEditarGraduaciones {
            get {
                return ResourceManager.GetString("TituloEditarGraduaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Habilidades.
        /// </summary>
        internal static string TituloEditarHabilidades {
            get {
                return ResourceManager.GetString("TituloEditarHabilidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando historial externo.
        /// </summary>
        internal static string TituloEditarHistorialExterno {
            get {
                return ResourceManager.GetString("TituloEditarHistorialExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Historial Seleccionado.
        /// </summary>
        internal static string TituloEditarHistorialLaboral {
            get {
                return ResourceManager.GetString("TituloEditarHistorialLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Jornada Laboral.
        /// </summary>
        internal static string TituloEditarJornadaLaboral {
            get {
                return ResourceManager.GetString("TituloEditarJornadaLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Certificacion.
        /// </summary>
        internal static string TituloEditarMaestroCertificacion {
            get {
                return ResourceManager.GetString("TituloEditarMaestroCertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Modulo.
        /// </summary>
        internal static string TituloEditarModulo {
            get {
                return ResourceManager.GetString("TituloEditarModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Nomina.
        /// </summary>
        internal static string TituloEditarNomina {
            get {
                return ResourceManager.GetString("TituloEditarNomina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Página.
        /// </summary>
        internal static string TituloEditarPaginas {
            get {
                return ResourceManager.GetString("TituloEditarPaginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Perfil.
        /// </summary>
        internal static string TituloEditarPerfil {
            get {
                return ResourceManager.GetString("TituloEditarPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Presupuesto.
        /// </summary>
        internal static string TituloEditarPresupuesto {
            get {
                return ResourceManager.GetString("TituloEditarPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editando Proveedor.
        /// </summary>
        internal static string TituloEditarProveedor {
            get {
                return ResourceManager.GetString("TituloEditarProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Sociedad.
        /// </summary>
        internal static string TituloEditarSociedad {
            get {
                return ResourceManager.GetString("TituloEditarSociedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Software.
        /// </summary>
        internal static string TituloEditarSoftware {
            get {
                return ResourceManager.GetString("TituloEditarSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Software/Modulo.
        /// </summary>
        internal static string TituloEditarSoftwareModulo {
            get {
                return ResourceManager.GetString("TituloEditarSoftwareModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Unidad Negocio.
        /// </summary>
        internal static string TituloEditarUnidadesNegocio {
            get {
                return ResourceManager.GetString("TituloEditarUnidadesNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Unidades Organizacionales.
        /// </summary>
        internal static string TituloEditarUnidadesOrganizacional {
            get {
                return ResourceManager.GetString("TituloEditarUnidadesOrganizacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        internal static string TituloEditarUsuario {
            get {
                return ResourceManager.GetString("TituloEditarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario Perfil.
        /// </summary>
        internal static string TituloEditarUsuarioPerfil {
            get {
                return ResourceManager.GetString("TituloEditarUsuarioPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Generales.
        /// </summary>
        internal static string TituloEvento {
            get {
                return ResourceManager.GetString("TituloEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eventos Costos.
        /// </summary>
        internal static string TituloEventoCostos {
            get {
                return ResourceManager.GetString("TituloEventoCostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Familia Competencias.
        /// </summary>
        internal static string TituloFamiliaCompetencias {
            get {
                return ResourceManager.GetString("TituloFamiliaCompetencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competencias Conductuales.
        /// </summary>
        internal static string TituloGrillaCursoCompetenciaConductuales {
            get {
                return ResourceManager.GetString("TituloGrillaCursoCompetenciaConductuales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Competencias Técnicas.
        /// </summary>
        internal static string TituloGrillaCursoCompetenciasTecnicas {
            get {
                return ResourceManager.GetString("TituloGrillaCursoCompetenciasTecnicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lugar de Ejecución.
        /// </summary>
        internal static string TituloHorario {
            get {
                return ResourceManager.GetString("TituloHorario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imputar costos al evento.
        /// </summary>
        internal static string TituloImputarCostos {
            get {
                return ResourceManager.GetString("TituloImputarCostos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Items a la Competencia.
        /// </summary>
        internal static string TituloItemsCompetenciasAdd {
            get {
                return ResourceManager.GetString("TituloItemsCompetenciasAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Items de la Competencia.
        /// </summary>
        internal static string TituloItemsCompetenciasEdit {
            get {
                return ResourceManager.GetString("TituloItemsCompetenciasEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Capacitación.
        /// </summary>
        internal static string TituloNuevaCapacitacion {
            get {
                return ResourceManager.GetString("TituloNuevaCapacitacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar un nueva Competencia.
        /// </summary>
        internal static string TituloNuevaCompentencia {
            get {
                return ResourceManager.GetString("TituloNuevaCompentencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo estudio.
        /// </summary>
        internal static string TituloNuevaEstudio {
            get {
                return ResourceManager.GetString("TituloNuevaEstudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo resultado de procesos de evaluación del desempeño.
        /// </summary>
        internal static string TituloNuevaEvaluacionDesempeno {
            get {
                return ResourceManager.GetString("TituloNuevaEvaluacionDesempeno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Función.
        /// </summary>
        internal static string TituloNuevaFunción {
            get {
                return ResourceManager.GetString("TituloNuevaFunción", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo {0}.
        /// </summary>
        internal static string TituloNuevoAbstractTableEditor {
            get {
                return ResourceManager.GetString("TituloNuevoAbstractTableEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Registro de Activo.
        /// </summary>
        internal static string TituloNuevoActivo {
            get {
                return ResourceManager.GetString("TituloNuevoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Antecedente de Salud Ocupacional.
        /// </summary>
        internal static string TituloNuevoAntecedenteSalud {
            get {
                return ResourceManager.GetString("TituloNuevoAntecedenteSalud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cargo.
        /// </summary>
        internal static string TituloNuevoCargo {
            get {
                return ResourceManager.GetString("TituloNuevoCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Certificación.
        /// </summary>
        internal static string TituloNuevoCertificacionHabilidadesCargo {
            get {
                return ResourceManager.GetString("TituloNuevoCertificacionHabilidadesCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cliente.
        /// </summary>
        internal static string TituloNuevoCliente {
            get {
                return ResourceManager.GetString("TituloNuevoCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cliente Software.
        /// </summary>
        internal static string TituloNuevoClienteSoftware {
            get {
                return ResourceManager.GetString("TituloNuevoClienteSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cliente Software Módulos.
        /// </summary>
        internal static string TituloNuevoClienteSoftwareModulos {
            get {
                return ResourceManager.GetString("TituloNuevoClienteSoftwareModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cliente Software Users.
        /// </summary>
        internal static string TituloNuevoClienteSoftwareUsers {
            get {
                return ResourceManager.GetString("TituloNuevoClienteSoftwareUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Cliente/Usuarios.
        /// </summary>
        internal static string TituloNuevoClienteUsers {
            get {
                return ResourceManager.GetString("TituloNuevoClienteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Comentario.
        /// </summary>
        internal static string TituloNuevoComentario {
            get {
                return ResourceManager.GetString("TituloNuevoComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Conducta.
        /// </summary>
        internal static string TituloNuevoConducta {
            get {
                return ResourceManager.GetString("TituloNuevoConducta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Contrato.
        /// </summary>
        internal static string TituloNuevoContrato {
            get {
                return ResourceManager.GetString("TituloNuevoContrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo documento.
        /// </summary>
        internal static string TituloNuevoDocumento {
            get {
                return ResourceManager.GetString("TituloNuevoDocumento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Generales.
        /// </summary>
        internal static string TituloNuevoEvento {
            get {
                return ResourceManager.GetString("TituloNuevoEvento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Familia Cargo.
        /// </summary>
        internal static string TituloNuevoFamiliaCargo {
            get {
                return ResourceManager.GetString("TituloNuevoFamiliaCargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Familia Competencia.
        /// </summary>
        internal static string TituloNuevoFamiliaCompetencia {
            get {
                return ResourceManager.GetString("TituloNuevoFamiliaCompetencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Funcionalidades.
        /// </summary>
        internal static string TituloNuevoFuncionalidades {
            get {
                return ResourceManager.GetString("TituloNuevoFuncionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Graduación.
        /// </summary>
        internal static string TituloNuevoGraduacion {
            get {
                return ResourceManager.GetString("TituloNuevoGraduacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Historial Interno.
        /// </summary>
        internal static string TituloNuevoHistoriaInterna {
            get {
                return ResourceManager.GetString("TituloNuevoHistoriaInterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar experiencia laboral externa.
        /// </summary>
        internal static string TituloNuevoHistorialExterno {
            get {
                return ResourceManager.GetString("TituloNuevoHistorialExterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Jornada Laboral.
        /// </summary>
        internal static string TituloNuevoJornadaLaboral {
            get {
                return ResourceManager.GetString("TituloNuevoJornadaLaboral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Certificación.
        /// </summary>
        internal static string TituloNuevoMaestroCertificacion {
            get {
                return ResourceManager.GetString("TituloNuevoMaestroCertificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Módulo Página Funcionalidad.
        /// </summary>
        internal static string TituloNuevoModuloPaginaFuncionalidad {
            get {
                return ResourceManager.GetString("TituloNuevoModuloPaginaFuncionalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Módulos.
        /// </summary>
        internal static string TituloNuevoModulos {
            get {
                return ResourceManager.GetString("TituloNuevoModulos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Página.
        /// </summary>
        internal static string TituloNuevoPaginas {
            get {
                return ResourceManager.GetString("TituloNuevoPaginas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Participantes.
        /// </summary>
        internal static string TituloNuevoParticipante {
            get {
                return ResourceManager.GetString("TituloNuevoParticipante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Perfil.
        /// </summary>
        internal static string TituloNuevoPerfil {
            get {
                return ResourceManager.GetString("TituloNuevoPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Prespuesto.
        /// </summary>
        internal static string TituloNuevoPresupuesto {
            get {
                return ResourceManager.GetString("TituloNuevoPresupuesto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Proveedor.
        /// </summary>
        internal static string TituloNuevoProveedor {
            get {
                return ResourceManager.GetString("TituloNuevoProveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Sociedad.
        /// </summary>
        internal static string TituloNuevoSociedad {
            get {
                return ResourceManager.GetString("TituloNuevoSociedad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Software.
        /// </summary>
        internal static string TituloNuevoSoftware {
            get {
                return ResourceManager.GetString("TituloNuevoSoftware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Software Módulo.
        /// </summary>
        internal static string TituloNuevoSoftwareModulo {
            get {
                return ResourceManager.GetString("TituloNuevoSoftwareModulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Unidad Negocio.
        /// </summary>
        internal static string TituloNuevoUnidadesNegocio {
            get {
                return ResourceManager.GetString("TituloNuevoUnidadesNegocio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Unidad Organizacional.
        /// </summary>
        internal static string TituloNuevoUnidadesOrganizacional {
            get {
                return ResourceManager.GetString("TituloNuevoUnidadesOrganizacional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Users.
        /// </summary>
        internal static string TituloNuevoUsers {
            get {
                return ResourceManager.GetString("TituloNuevoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agrega Usuario Perfil.
        /// </summary>
        internal static string TituloNuevoUsuarioPerfil {
            get {
                return ResourceManager.GetString("TituloNuevoUsuarioPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Código Sence.
        /// </summary>
        internal static string TituloSeleccionarCodigoSence {
            get {
                return ResourceManager.GetString("TituloSeleccionarCodigoSence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Catálogo.
        /// </summary>
        internal static string TituloSeleccionCursoCatalo {
            get {
                return ResourceManager.GetString("TituloSeleccionCursoCatalo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        internal static string WizardCancel {
            get {
                return ResourceManager.GetString("WizardCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar.
        /// </summary>
        internal static string WizardImport {
            get {
                return ResourceManager.GetString("WizardImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Siguiente.
        /// </summary>
        internal static string WizardNext {
            get {
                return ResourceManager.GetString("WizardNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anterior.
        /// </summary>
        internal static string WizardPrevious {
            get {
                return ResourceManager.GetString("WizardPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Validar.
        /// </summary>
        internal static string WizardValidate {
            get {
                return ResourceManager.GetString("WizardValidate", resourceCulture);
            }
        }
    }
}
